"""CLAUDE.md bridge -- assembles knowledge base content into a structured
CLAUDE.md file for a target project directory.

Pulls from two sources:
- knowledge/ (agent-managed): files tagged project:<name>
- knowledge_canon/ (user-managed, read-only): files tagged project:<name>

Excludes files tagged private or secret from both sources.
Writes a complete CLAUDE.md to the target project path. Full regeneration
on each call -- no merge, no diffing.

Inclusion strategy:
1. Score all candidate files by weighted priority:
   - Recency: exponential decay on last_modified (30-day half-life)
   - Canon bonus: 2x multiplier (authoritative source)
2. Sort by score descending.
3. Greedily fill the budget (default 64KB):
   - Include full content if it fits in remaining budget.
   - Include truncated content if remaining budget >= FILE_MIN_CHARS and
     truncation would still leave meaningful content.
   - Skip the file if the remaining budget is below the floor.
4. Append a summary of any skipped files.

Relative project paths resolve to PROJECT_OUTPUTS_PATH.
"""

import math
from datetime import datetime, timezone
from pathlib import Path

from agent.config import KNOWLEDGE_CANON_PATH, PROJECT_OUTPUTS_PATH, CLAUDE_MD_MAX_CHARS
from knowledge.knowledge_store import list_files, read_file

_CANON_DIR = Path(KNOWLEDGE_CANON_PATH)
_OUTPUTS_DIR = Path(PROJECT_OUTPUTS_PATH)

# Minimum chars of content worth including after truncation.
# A section smaller than this is more noise than signal.
FILE_MIN_CHARS = 400

# Separator overhead between sections (approximate)
_SEPARATOR = "\n\n---\n\n"
_SEPARATOR_LEN = len(_SEPARATOR)


def _collect_files(project_name: str) -> list[dict]:
    """Collect knowledge files relevant to a project.

    Pulls from both knowledge/ and knowledge_canon/. Only includes files
    explicitly tagged project:<project_name>. Excludes private/secret.
    Canon files are marked with source="canon" in metadata.
    """
    project_tag = f"project:{project_name}"
    exclude = ["private", "secret"]

    kb_files = list_files(filter_tags=[project_tag], exclude_tags=exclude)
    for f in kb_files:
        f["source"] = "knowledge"

    canon_files = list_files(
        filter_tags=[project_tag], exclude_tags=exclude, base_dir=_CANON_DIR,
    )
    for f in canon_files:
        f["source"] = "canon"

    return kb_files + canon_files


def _score_file(file_info: dict) -> float:
    """Score a file for inclusion priority. Higher score = higher priority.

    Recency: exponential decay based on last_modified. Half-life of 30 days --
    a file updated today scores 1.0; one updated 30 days ago scores 0.5;
    90 days ago scores ~0.125. Uses last_modified, not date created.

    Canon bonus: 2x multiplier. Canon files are authoritative and should
    survive budget cuts over knowledge files of similar age.
    """
    last_modified = file_info.get("last_modified", "")
    try:
        mod_dt = datetime.fromisoformat(last_modified)
        if mod_dt.tzinfo is None:
            mod_dt = mod_dt.replace(tzinfo=timezone.utc)
        days_old = (datetime.now(timezone.utc) - mod_dt).total_seconds() / 86400
    except Exception:
        days_old = 365  # treat unparseable dates as old

    recency = math.exp(-days_old * math.log(2) / 30)
    canon_multiplier = 2.0 if file_info.get("source") == "canon" else 1.0
    return recency * canon_multiplier


def _build_section(file_info: dict, content_limit: int) -> str:
    """Build a markdown section for one knowledge file.

    content_limit: max chars to include from the file body. Pass sys.maxsize
    (or a very large number) for uncapped. Returns empty string if the file
    has no content.
    """
    filename = file_info["filename"]
    tags = file_info.get("tags", [])
    last_modified = file_info.get("last_modified", "unknown")
    source = file_info.get("source", "knowledge")

    base_dir = _CANON_DIR if source == "canon" else None
    content = read_file(filename, base_dir=base_dir)
    if not content:
        return ""

    truncated = False
    if len(content) > content_limit:
        content = content[:content_limit]
        truncated = True

    stem = filename.replace(".md", "")
    tag_str = ", ".join(tags) if tags else "none"

    lines = [
        f"### {stem}",
        f"Tags: {tag_str} | Updated: {last_modified}",
        "",
        content,
    ]

    if truncated:
        lines.append("")
        lines.append(
            "(Truncated -- full content available via the local API: "
            f"GET /knowledge/{filename})"
        )

    return "\n".join(lines)


def generate_claude_md(project_name: str) -> str:
    """Generate the full CLAUDE.md content for a project.

    Returns the assembled markdown string.
    """
    files = _collect_files(project_name)

    header = (
        "# Project Context (Agent Zero)\n\n"
        "This file is auto-generated by Agent Zero from its knowledge base.\n"
        "Manual edits will be overwritten on the next update.\n"
        "Source of truth: the knowledge base, not this file.\n"
    )

    if not files:
        return header + "\n(No knowledge files found for this project.)\n"

    # Score and sort. Higher score = higher inclusion priority.
    for f in files:
        f["_score"] = _score_file(f)
    files.sort(key=lambda f: f["_score"], reverse=True)

    sections: list[str] = []
    skipped: list[str] = []
    budget = CLAUDE_MD_MAX_CHARS - len(header) - len(_SEPARATOR)

    for f in files:
        filename = f["filename"]
        source = f.get("source", "knowledge")
        base_dir = _CANON_DIR if source == "canon" else None
        raw_content = read_file(filename, base_dir=base_dir)
        if not raw_content:
            continue

        # Estimate full section size (header lines ~80 chars, separator overhead)
        section_overhead = 80
        full_size = len(raw_content) + section_overhead

        if full_size <= budget:
            # Fits whole -- include at full length
            section = _build_section(f, len(raw_content))
            if section:
                sections.append(section)
                budget -= len(section) + _SEPARATOR_LEN
        elif budget >= FILE_MIN_CHARS + section_overhead:
            # Partial fit -- truncate to remaining budget minus overhead
            limit = budget - section_overhead
            section = _build_section(f, limit)
            if section:
                sections.append(section)
                budget -= len(section) + _SEPARATOR_LEN
        else:
            # Budget exhausted -- record as skipped
            skipped.append(filename)

    body = _SEPARATOR.join(sections) if sections else "(No content.)"

    result = header + "\n---\n\n" + body + "\n"

    if skipped:
        skipped_note = (
            "\n---\n\n"
            f"({len(skipped)} knowledge file(s) omitted -- budget exhausted. "
            "Query the local API for full access: "
            + ", ".join(skipped)
            + ")"
        )
        result += skipped_note

    return result


def write_claude_md(project_path: str, project_name: str) -> str:
    """Generate and write CLAUDE.md to a project directory.

    Relative paths resolve to PROJECT_OUTPUTS_PATH. Absolute paths are
    used as-is.

    Args:
        project_path: Path to the target project directory. Relative paths
            are resolved under project_outputs/ in the project root.
        project_name: Name used to match project:<name> tags.

    Returns the path of the written file.
    """
    target_dir = Path(project_path).expanduser()
    if not target_dir.is_absolute():
        target_dir = _OUTPUTS_DIR / target_dir

    target_dir.mkdir(parents=True, exist_ok=True)

    content = generate_claude_md(project_name)
    target = target_dir / "CLAUDE.md"
    target.write_text(content, encoding="utf-8")
    return str(target)
