"""CLAUDE.md bridge -- assembles knowledge base content into a structured
CLAUDE.md file for a target project directory.

Pulls from two sources:
- knowledge/ (agent-managed): files tagged project:<name>
- knowledge_canon/ (user-managed, read-only): files tagged project:<name>

Excludes files tagged private or secret from both sources.
Writes a complete CLAUDE.md to the target project path. Full regeneration
on each call -- no merge, no diffing.

Size target: under 4000 tokens (~16KB). If total content exceeds the budget,
only the most recently modified files are included, and each file's content
is truncated to ~2KB with a note that the full file is available via the API.
"""

from pathlib import Path

from agent.config import KNOWLEDGE_CANON_PATH
from knowledge.knowledge_store import list_files, read_file

_CANON_DIR = Path(KNOWLEDGE_CANON_PATH)

# Rough estimate: 1 token ~= 4 chars. 4000 tokens ~= 16000 chars.
MAX_CHARS = 16000
FILE_CONTENT_CAP = 2000  # ~500 tokens per file


def _collect_files(project_name: str) -> list[dict]:
    """Collect knowledge files relevant to a project.

    Pulls from both knowledge/ and knowledge_canon/. Only includes files
    explicitly tagged project:<project_name>. Excludes private/secret.
    Canon files are marked with source="canon" in metadata.
    """
    project_tag = f"project:{project_name}"
    exclude = ["private", "secret"]

    kb_files = list_files(filter_tags=[project_tag], exclude_tags=exclude)
    for f in kb_files:
        f["source"] = "knowledge"

    canon_files = list_files(
        filter_tags=[project_tag], exclude_tags=exclude, base_dir=_CANON_DIR,
    )
    for f in canon_files:
        f["source"] = "canon"

    # Canon files first (authoritative), then knowledge files
    return canon_files + kb_files


def _build_section(file_info: dict) -> str:
    """Build a markdown section for one knowledge file.

    Returns the section text or empty string if the file has no content.
    """
    filename = file_info["filename"]
    tags = file_info.get("tags", [])
    last_modified = file_info.get("last_modified", "unknown")
    source = file_info.get("source", "knowledge")

    base_dir = _CANON_DIR if source == "canon" else None
    content = read_file(filename, base_dir=base_dir)
    if not content:
        return ""

    # Truncate if over the per-file cap
    truncated = False
    if len(content) > FILE_CONTENT_CAP:
        content = content[:FILE_CONTENT_CAP]
        truncated = True

    stem = filename.replace(".md", "")
    tag_str = ", ".join(tags) if tags else "none"

    lines = [
        f"### {stem}",
        f"Tags: {tag_str} | Updated: {last_modified}",
        "",
        content,
    ]

    if truncated:
        lines.append("")
        lines.append(
            "(Truncated -- full content available via the local API: "
            f"GET /knowledge/{filename})"
        )

    return "\n".join(lines)


def generate_claude_md(project_name: str) -> str:
    """Generate the full CLAUDE.md content for a project.

    Returns the assembled markdown string.
    """
    files = _collect_files(project_name)

    header = (
        "# Project Context (Agent Zero)\n\n"
        "This file is auto-generated by Agent Zero from its knowledge base.\n"
        "Manual edits will be overwritten on the next update.\n"
        "Source of truth: the knowledge base, not this file.\n"
    )

    if not files:
        return header + "\n(No knowledge files found for this project.)\n"

    sections = []
    total_chars = len(header)

    for f in files:
        section = _build_section(f)
        if not section:
            continue

        # Check if adding this section would exceed the budget
        if total_chars + len(section) + 10 > MAX_CHARS:
            sections.append(
                "\n---\n\n(Additional knowledge files omitted to stay within "
                "context budget. Query the local API for full access.)\n"
            )
            break

        sections.append(section)
        total_chars += len(section) + 10  # account for separators

    body = "\n\n---\n\n".join(sections) if sections else "(No content.)"
    return header + "\n---\n\n" + body + "\n"


def write_claude_md(project_path: str, project_name: str) -> str:
    """Generate and write CLAUDE.md to a project directory.

    Args:
        project_path: Absolute path to the target project directory.
        project_name: Name used to match project:<name> tags.

    Returns the path of the written file.
    """
    target_dir = Path(project_path).expanduser()
    target_dir.mkdir(parents=True, exist_ok=True)

    content = generate_claude_md(project_name)
    target = target_dir / "CLAUDE.md"
    target.write_text(content, encoding="utf-8")
    return str(target)
